name: ABMCHorse
version: 1.4
main: me.mastergabemod.horse.HorsePlugin
description: Spawn a horse on your location
author: MasterGabeMOD
authors:
  - Akutasan

commands:
  witherhorse:
    description: Mount a horse.
permissions:
  horse.use:
    description: Use /horse